### ISSUE TITLE
useContext doesn't always correctly rerender

### ISSUE THREAD

**Issue by janpaul123** [yesmeck/react-with-hooks#3]
Specifically, when you have a nesting like this: `Provider -> SomeComponent -> ComponentWithUseContext` where `SomeComponent` has `shouldComponentUpdate = () => false;` then `ComponentWithUseContext` doesn't properly rerender when `Provider` gets a new value (whereas using `<Consumer>` does rerender in that case).

**Comment by yesmeck** [comment]
Unfortunately, after hours trying, I could not find a proper way to implement `useContext`.

**Comment by janpaul123** [comment]
Wow amazing, nice work!! Thank you!
